name: e2e test
on:
  pull_request:
    branches:
     - main
  push:
    branches:
     - main

jobs:
  e2e:
    name: e2e test
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
  
      - name: Prepare the test oci registry
        run: |
          ./scripts/reg.sh
          ./scripts/e2e_prepare.sh
    
      - name: Login to ghcr.io
        run: |
          ./bin/kpm login -u ${{ secrets.DEPLOY_ACCESS_NAME }} -p ${{ secrets.DEPLOY_ACCESS_TOKEN }} ghcr.io

      - name: Login to docker.io
        run: |
          ./bin/kpm login -u ${{ secrets.DEPLOY_ACCESS_NAME }} -p ${{ secrets.DEPLOY_ACCESS_TOKEN }} docker.io

      - name: run e2e
        run: |
          make e2e
